python3 ./delcluster/delmanagement.py &
python3 ./delcluster/m1.py &
python3 ./delcluster/m2.py &
python3 ./delcluster/m3.py &
python3 ./delcluster/m4.py &
python3 ./delcluster/m5.py &
python3 ./delcluster/m6.py &
python3 ./delcluster/m7.py &
python3 ./delcluster/m8.py &
python3 ./delcluster/m9.py &
python3 ./delcluster/m10.py &
python3 ./delcluster/m11.py &
python3 ./delcluster/m12.py &
python3 ./delcluster/m13.py &
python3 ./delcluster/m14.py &
python3 ./delcluster/m15.py &
python3 ./delcluster/m16.py &
python3 ./delcluster/m17.py &
python3 ./delcluster/m18.py &
python3 ./delcluster/m19.py &
python3 ./delcluster/m20.py &