- hosts: all
  become: yes
  tasks:
  - name: Remove swapfile from /etc/fstab
    mount:
      name: swap
      fstype: swap
      state: absent

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0
    
  - name: set up authorized keys for root user
    authorized_key: user=root key="{{item}}"
    with_file:
      - ~/.ssh/id_rsa.pub

  - name: Assign inventory name to unconfigured hostnames (non-CoreOS, Suse and ClearLinux)
    hostname:
      name: "{{ inventory_hostname }}"

  - name: "Add IP address of all hosts to all hosts"
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_host }} {{item}}"
      state: present
    when: hostvars[item].ansible_host is defined
    with_items: "{{ groups.all }}"

- hosts: all[0]
  become: yes
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --kubernetes-version v1.32.1

    - name: create .kube directory
      become: yes
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        owner: root

- hosts: all[0]
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: all[1:]
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars[groups['all'][0]].join_command }}"